# RIP grep
#
# Ripgrep has no default config path. 
# It only reads a config file if RIPGREP_CONFIG_PATH is explicitly set. 
#
# No inline comments allowed.

# Search case insensitively if the pattern is all lowercase.
--smart-case        

# Search hidden files and directories. By default, they are skipped.
--hidden            

