# ~/.config/lsd/config_tty.yaml

# icons off in TTY
icons:
  when: never

# Use colors to differentiate file types
color:
  when: always
  theme: default

# Add indicators (like / for directories) to help navigation without icons
indicators: true

sorting:
  column: name
  dir-first: true
  version-sort: true

# Clean layout
layout: grid

date: relative

# Permission format (rwx or octal)
permission: rwx

